services:
  - type: web
    name: fake-identification-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: UPLOAD_DIR
        value: ./tmp_uploads
    autoDeploy: true
