FROM python:3.10-slim

WORKDIR /app/ml/training

# Install dependencies required for Pillow and PyTorch
RUN apt-get update && apt-get install -y \
    libglib2.0-0 libsm6 libxext6 libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "train_tamper_cnn.py"]
